import 'package:firebase_auth/firebase_auth.dart';
import 'package:hive_ce/hive.dart';

part 'user_cred.g.dart'; // This will be generated by Hive

@HiveType(typeId: 11) // Ensure this typeId is unique
class UserCred {
  @HiveField(0)
  final String uid;

  @HiveField(1)
  final String? email;

  @HiveField(2)
  final String? displayName;

  @HiveField(3)
  final String? photoURL;

  @HiveField(4)
  final String? phoneNumber;

  @HiveField(5)
  final bool emailVerified;

  UserCred({
    required this.uid,
    this.email,
    this.displayName,
    this.photoURL,
    this.phoneNumber,
    required this.emailVerified,
  });

  // Factory method to create a UserCred from a Firebase User object
  factory UserCred.fromFirebaseUser(User user) {
    return UserCred(
      uid: user.uid,
      email: user.email,
      displayName: user.displayName,
      photoURL: user.photoURL,
      phoneNumber: user.phoneNumber,
      emailVerified: user.emailVerified,
    );
  }
}
