// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE-Xs9hxajIGhzVzHZc0el0wYA7IMvbhw',
    appId: '1:893158041520:web:89c313b8134a4d60b55875',
    messagingSenderId: '893158041520',
    projectId: 'sudoku-mania-ac224',
    authDomain: 'sudoku-mania-ac224.firebaseapp.com',
    storageBucket: 'sudoku-mania-ac224.firebasestorage.app',
    measurementId: 'G-P22QV5SK3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByZUU0_D5VNzZwFJSK-PSbi6GrDdOp-z8',
    appId: '1:893158041520:android:08b6e7c321be48bfb55875',
    messagingSenderId: '893158041520',
    projectId: 'sudoku-mania-ac224',
    storageBucket: 'sudoku-mania-ac224.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIBxVYVRozxACZdTrRlxb1azHVG_nsEwk',
    appId: '1:893158041520:ios:fb38f7b1908c0583b55875',
    messagingSenderId: '893158041520',
    projectId: 'sudoku-mania-ac224',
    storageBucket: 'sudoku-mania-ac224.firebasestorage.app',
    iosBundleId: 'com.example.sudokumania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIBxVYVRozxACZdTrRlxb1azHVG_nsEwk',
    appId: '1:893158041520:ios:fb38f7b1908c0583b55875',
    messagingSenderId: '893158041520',
    projectId: 'sudoku-mania-ac224',
    storageBucket: 'sudoku-mania-ac224.firebasestorage.app',
    iosBundleId: 'com.example.sudokumania',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE-Xs9hxajIGhzVzHZc0el0wYA7IMvbhw',
    appId: '1:893158041520:web:7c8636c1efa7c49cb55875',
    messagingSenderId: '893158041520',
    projectId: 'sudoku-mania-ac224',
    authDomain: 'sudoku-mania-ac224.firebaseapp.com',
    storageBucket: 'sudoku-mania-ac224.firebasestorage.app',
    measurementId: 'G-4P3DV9YFHB',
  );

}