// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:sudokumania/models/game_progress.dart';
import 'package:sudokumania/models/sudoku_board.dart';
import 'package:sudokumania/models/userModel.dart';
import 'package:sudokumania/models/user_stats.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CurrentGameProgressAdapter());
    registerAdapter(DifficultyStatsAdapter());
    registerAdapter(GameHistoryAdapter());
    registerAdapter(GameProgressAdapter());
    registerAdapter(SudokuBoardAdapter());
    registerAdapter(UserDataAdapter());
    registerAdapter(UserStatsAdapter());
  }
}
