// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:sudokumania/models/userModel.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DifficultyStatsAdapter());
    registerAdapter(GameHistoryAdapter());
    registerAdapter(GameProgressAdapter());
    registerAdapter(UserDataAdapter());
  }
}
