// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:sudokumania/models/dailyChallenges%20Models/daily_challenge_progress.dart';
import 'package:sudokumania/models/gameProgress%20Models/game_progress.dart';
import 'package:sudokumania/models/sudokuBoardModels/sudoku_board.dart';
import 'package:sudokumania/models/themeSwitch%20Models/themeModel.dart';
import 'package:sudokumania/models/userCredential%20Models/user_cred.dart';
import 'package:sudokumania/models/userStats%20Models/userModel.dart';
import 'package:sudokumania/models/userStats%20Models/user_stats.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CurrentGameProgressAdapter());
    registerAdapter(DailyChallengeProgressAdapter());
    registerAdapter(DifficultyStatsAdapter());
    registerAdapter(GameHistoryAdapter());
    registerAdapter(GameProgressAdapter());
    registerAdapter(SudokuBoardAdapter());
    registerAdapter(ThemePreferenceAdapter());
    registerAdapter(UserCredAdapter());
    registerAdapter(UserDataAdapter());
    registerAdapter(UserStatsAdapter());
  }
}
